import { ICON_REGISTRY, type IconName } from './iconRegistry';

/**
 * LỚP CHUYỂN TIẾP (chuẩn hoá icon 2026-10-06): tên icon KIỂU CŨ (tên hình, dạng kebab của
 * components/common/Icon.tsx) → tên CHỨC NĂNG trong iconRegistry.
 *
 * Cần vì tên cũ còn chảy qua dữ liệu (vd `constants.ts` khai `icon: 'trending-up'` cho từng thẻ KPI)
 * vào các component dùng chung (`Input leftIcon`, `KpiCard icon`…). Các biến thể của cùng chức năng
 * dồn về MỘT tên: 'trash-2' → delete, 'check-circle'/'check-circle-2' → success, 'refresh-ccw'/
 * 'refresh-cw' → refresh, 'settings'/'settings-2' → settings…
 *
 * Có thêm 6 tên mà bảng cũ KHÔNG có nên từng âm thầm hiện dấu hỏi: 'alert-octagon', 'trending-down',
 * 'message-square', 'arrow-up-narrow-wide', 'arrow-down-wide-narrow', 'user-plus'. KHÔNG xoá file này dù `iconLegacyCall` đã về 0 (2026-10-07): tên cũ còn nằm trong DỮ LIỆU người
 * dùng đã lưu (cấu hình thẻ KPI, cột tuỳ chỉnh… trên IndexedDB/Firestore), không chỉ trong code.
 */
export const LEGACY_ICON_NAMES: Record<string, IconName> = {
  'activity': 'activity',
  'alert-circle': 'alert',
  'alert-triangle': 'warning',
  'alert-octagon': 'error',
  'apple': 'apple',
  'archive-restore': 'restore',
  'area-chart': 'chartLine',
  'arrow-down': 'arrowDown',
  'arrow-right': 'next',
  'arrow-up': 'arrowUp',
  'award': 'award',
  'backpack': 'backpack',
  'banknote': 'cash',
  'bar-chart-2': 'chartBar',
  'bar-chart-3': 'chartBar',
  'bar-chart-horizontal': 'chartBar',
  'battery-charging': 'battery',
  'bell': 'notification',
  'bell-off': 'notificationOff',
  'blender': 'appliance',
  'box': 'product',
  'briefcase': 'briefcase',
  'bug': 'bug',
  'cable': 'accessory',
  'calculator': 'calculator',
  'calendar': 'calendar',
  'calendar-clock': 'schedule',
  'calendar-days': 'calendar',
  'calendar-check': 'calendarCheck',
  'calendar-x': 'calendarOff',
  'camera': 'exportImage',
  'check': 'check',
  'check-circle': 'success',
  'check-circle-2': 'success',
  'check-square': 'checkboxOn',
  'chef-hat': 'kitchen',
  'chevron-down': 'chevronDown',
  'chevron-left': 'chevronLeft',
  'chevron-right': 'chevronRight',
  'chevron-up': 'chevronUp',
  'chevrons-down-up': 'collapseAll',
  'chevrons-up-down': 'expandAll',
  'circle-dollar-sign': 'money',
  'clipboard-list': 'checklist',
  'clipboard-paste': 'paste',
  'clock': 'clock',
  'cloud-download': 'cloudDownload',
  'code': 'code',
  'coffee': 'coffee',
  'columns': 'columns',
  'columns-2': 'columns',
  'compass': 'compass',
  'contact': 'contact',
  'copy': 'copy',
  'cpu': 'cpu',
  'credit-card': 'card',
  'crown': 'crown',
  'database': 'database',
  'dollar-sign': 'money',
  'download': 'download',
  'download-cloud': 'cloudDownload',
  'droplet': 'water',
  'droplets': 'water',
  'edit-3': 'edit',
  'external-link': 'externalLink',
  'eye': 'show',
  'eye-off': 'hide',
  'factory': 'factory',
  'fan': 'fan',
  'fast-forward': 'fastForward',
  'file-check': 'fileCheck',
  'file-key-2': 'fileKey',
  'file-scan': 'fileScan',
  'file-spreadsheet': 'spreadsheet',
  'file-text': 'report',
  'file-up': 'upload',
  'film': 'film',
  'filter': 'filter',
  'flame': 'flame',
  'gift': 'gift',
  'gallery-horizontal-end': 'gallery',
  'gamepad-2': 'gamepad',
  'gantt-chart-square': 'gantt',
  'glasses': 'glasses',
  'grid': 'viewGrid',
  'grip-horizontal': 'dragHandle',
  'grip-vertical': 'dragHandle',
  'headphones': 'headphones',
  'help-circle': 'help',
  'history': 'history',
  'images': 'exportBatch',
  'inbox': 'empty',
  'info': 'info',
  'keyboard': 'keyboard',
  'laptop': 'laptop',
  'layers': 'layers',
  'layout': 'viewGrid',
  'layout-dashboard': 'dashboard',
  'layout-grid': 'viewGrid',
  'layout-list': 'viewList',
  'layout-template': 'template',
  'lightbulb': 'idea',
  'line': 'lineBrand',
  'line-app': 'lineBrand',
  'line-chart': 'chartLine',
  'link': 'link',
  'list': 'viewList',
  'list-todo': 'checklist',
  'loader-2': 'loading',
  'lock': 'lock',
  'log-out': 'logout',
  'map-pin': 'location',
  'maximize-2': 'expand',
  'medal': 'medal',
  'megaphone': 'announcement',
  'memory-stick': 'memory',
  'message-circle': 'message',
  'message-square': 'message',
  'more-vertical': 'more',
  'minimize-2': 'collapse',
  'mouse-pointer-2': 'pointer',
  'package': 'product',
  'package-x': 'productOff',
  'paintbrush': 'paintbrush',
  'palette': 'palette',
  'pencil': 'edit',
  'percent': 'percent',
  'pie-chart': 'chartPie',
  'play': 'play',
  'play-square': 'video',
  'plug-zap': 'appliance',
  'plus': 'add',
  'plus-circle': 'addCircle',
  'printer': 'print',
  'receipt': 'receipt',
  'refresh-ccw': 'refresh',
  'refresh-cw': 'refresh',
  'rocket': 'rocket',
  'rotate-ccw': 'reset',
  'router': 'router',
  'save': 'save',
  'scan-line': 'scan',
  'search': 'search',
  'search-x': 'searchEmpty',
  'server': 'server',
  'settings': 'settings',
  'settings-2': 'settings',
  'share-2': 'share',
  'sheet': 'spreadsheet',
  'shield': 'security',
  'shield-check': 'securityOk',
  'shopping-bag': 'shopping',
  'sigma': 'total',
  'signal': 'simCard',
  'sim-card': 'simCard',
  'sliders-horizontal': 'viewOptions',
  'smartphone': 'phone',
  'smartphone-nfc': 'phoneNfc',
  'sparkles': 'sparkles',
  'speaker': 'speaker',
  'square': 'checkboxOff',
  'star': 'star',
  'swords': 'compete',
  'table': 'table',
  'table-2': 'table',
  'tablet': 'tablet',
  'tag': 'tag',
  'target': 'target',
  'thermometer-snowflake': 'cooling',
  'tornado': 'tornado',
  'trash-2': 'delete',
  'trending-down': 'trendDown',
  'trending-up': 'trendUp',
  'trophy': 'trophy',
  'truck': 'delivery',
  'tv': 'tv',
  'type': 'font',
  'upload': 'upload',
  'upload-cloud': 'cloudUpload',
  'user': 'user',
  'user-check': 'userCheck',
  'user-cog': 'userSettings',
  'user-minus': 'userRemove',
  'user-round-check': 'userCheck',
  'user-round-x': 'userReject',
  'users': 'users',
  'users-round': 'users',
  'wallet': 'wallet',
  'wallet-cards': 'wallet',
  'warehouse': 'warehouse',
  'watch': 'watch',
  'waves': 'waves',
  'webcam': 'webcam',
  'wind': 'wind',
  'x': 'close',
  'zap': 'quick',
  // Tên KHÔNG có trong bảng cũ — từng âm thầm hiện dấu hỏi (phát hiện qua audit 2026-10-06)
  'arrow-up-narrow-wide': 'sortAsc',
  'arrow-down-wide-narrow': 'sortDesc',
  'user-plus': 'userAdd',
};

/** Tên chức năng giữ nguyên; tên cũ đổi qua bảng; không nhận ra → undefined (nơi gọi tự dự phòng). */
export function resolveIconName(name: string | undefined | null): IconName | undefined {
  if (!name) return undefined;
  if (name in ICON_REGISTRY) return name as IconName;
  return LEGACY_ICON_NAMES[name];
}
